stages:
  - test

test:
  stage: test

  script:
    - curl --location --request POST "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=test&ref=master" --header "PRIVATE-TOKEN:${GITLAB_TOKEN}"   
  only:
    - master